=== lcjohnso/pampelmuse/config/PMschema.xsd
<?xml version="1.0" encoding='ISO-8859-1'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.tobedefined.com/pampelmuse"
xmlns="http://www.tobedefined.com/pampelmuse"
elementFormDefault="qualified">

<xs:element name="configuration">
  <xs:complexType>
    <xs:sequence>
    <xs:element name="parameter" maxOccurs="unbounded" minOccurs="0">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="name" type="xs:string"/>
	    <xs:choice>
              <xs:element name="value"> <!-- type="xs:string">-->
		<xs:complexType>
		  <xs:simpleContent>
		    <xs:extension base="xs:string">
		      <xs:attribute name="dtype" type="xs:string"
				    use="required"/>
		    </xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	      </xs:element>
<!--              <xs:element name="string" type="xs:string"/>
              <xs:element name="float" type="xs:decimal"/>
              <xs:element name="integer" type="xs:int"/>
              <xs:element name="flag" type="xs:boolean"/> -->
	    </xs:choice>
          <xs:element name="comment" type="xs:string" maxOccurs="unbounded"
		      minOccurs="0"/>
	  <xs:element name="updated" maxOccurs="unbounded"
		      minOccurs="0">
	    <xs:complexType>
	      <xs:simpleContent>
		<xs:extension base="xs:string">
		  <xs:attribute name="timestamp" type="xs:dateTime"/>
		</xs:extension>
	      </xs:simpleContent>
	    </xs:complexType>
	  </xs:element>
        </xs:sequence>
<!--	<xs:attribute name="added" type="xs:date" use="required"/> -->
	<xs:attribute name="inuse" type="xs:boolean" default="true"/>
	<xs:attribute name="category" type="xs:string"/>
<!--	<xs:attribute name="updated" type="xs:date"/>
	<xs:attribute name="dtype" type="xs:string" use="required"/> -->
      </xs:complexType>
    </xs:element>
    </xs:sequence>
    <xs:attribute name="timestamp" type="xs:dateTime" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema>

=== lcjohnso/pampelmuse/pampelmuse/config/data/PMparams.xml
<?xml version="1.0" ?><?xml-stylesheet type="text/xsl" href="PMstyle.xsl"?><ns0:configuration timestamp="2014-12-03T15:12:14Z" xmlns:ns0="http://www.tobedefined.com/pampelmuse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tobedefined.com/pampelmuse PMschema.xsd">
 
 <ns0:parameter category="1pho" inuse="0">
  <ns0:name>CFPCOLS</ns0:name>
  <ns0:value dtype="tuple">(0, 1, 2, 3)</ns0:value>
  <ns0:comment>The columns of the crowded-field photometry file that contain: ID, x position, y position and magnitude of the stars</ns0:comment>
  <ns0:updated timestamp="2011-08-09T16:23:06Z">Appended parameter CFPCOLS to configuration file.</ns0:updated>
 <ns0:updated timestamp="2013-07-25T09:45:11Z">Disabled usage of parameter.</ns0:updated></ns0:parameter>
 <ns0:parameter category="1pho" inuse="1">
   <ns0:name>PASSBAND</ns0:name>
   <ns0:value dtype="str">F814W</ns0:value>
   <ns0:comment>The photometric passband in which the provided magnitudes are given</ns0:comment>
   <ns0:updated timestamp="2011-11-29T21:03:10Z">Appended parameter PASSBAND to configuration file.</ns0:updated>
  </ns0:parameter>
  <ns0:parameter category="1pho" inuse="1"><ns0:name>ZEROMAG</ns0:name><ns0:value dtype="float">99.9</ns0:value><ns0:comment>The magnitude zeropoint of the IFS data in the provided passband, i.e. the magnitude of a source triggering 1 count/layer. Set this parameter to 99.9 to let the routine determine the zeropoint from the data.</ns0:comment><ns0:updated timestamp="2013-06-10T20:45:38Z">Appended parameter ZEROMAG to configuration file.</ns0:updated></ns0:parameter><ns0:parameter category="1pho" inuse="1">
  <ns0:name>PIXSCALE</ns0:name>
  <ns0:value dtype="float">1.0</ns0:value>
  <ns0:comment>The spaxel scale if the observation. Note that this parameter is used only if PampelMuse can not determine the spaxel scale from the FITS header of the data.</ns0:comment><ns0:updated timestamp="2012-03-14T09:13:10Z">Appended parameter PIXSCALE to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="2sel" inuse="1">
  <ns0:name>APERRAD</ns0:name>
  <ns0:value dtype="float">3.0</ns0:value>
  <ns0:comment>Radius (in spaxels) used for aperture spectrophotometry</ns0:comment>
  <ns0:comment>Note that this parameter only has an effect if the SMALLIFU flag is unset.</ns0:comment><ns0:updated timestamp="2011-08-09T16:26:44Z">Appended parameter APERRAD to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="2sel" inuse="1">
  <ns0:name>APERNOIS</ns0:name>
  <ns0:value dtype="float">0.1</ns0:value>
  <ns0:comment>The maximum allowed fraction of contaminating flux within APERRAD. Aperture spectrophotometry is performed only for sources whose nearby neighbors contribute less than APERNOIS to the measured flux.</ns0:comment>
  <ns0:updated timestamp="2011-08-31T08:10:40Z">Appended parameter APERNOIS to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="2sel" inuse="1">
  <ns0:name>RESLIM</ns0:name>
  <ns0:value dtype="float">16.0</ns0:value>
  <ns0:comment>The magnitude down to which stars can possibly be resolved in the datacube.</ns0:comment>
  <ns0:updated timestamp="2011-08-31T08:13:37Z">Appended parameter RESLIM to configuration file.</ns0:updated>
 </ns0:parameter><ns0:parameter category="2sel" inuse="1"><ns0:name>UPDATERL</ns0:name><ns0:value dtype="bool">True</ns0:value><ns0:comment>If UPDATERL-flag is set, PampelMuse will determine the confusion limit and update RESLIM accordingly.</ns0:comment><ns0:updated timestamp="2012-04-16T16:49:15Z">Appended parameter UPDATERL to configuration file.</ns0:updated></ns0:parameter><ns0:parameter category="2sel" inuse="1"><ns0:name>CONFDENS</ns0:name><ns0:value dtype="float">0.4</ns0:value><ns0:comment>The confusion limit, i.e the number of stars per resultion element. A resolution element is defined as the FWHM \[pixel\] of the PSF squared. Only used if UPDATERL-flag is set.</ns0:comment><ns0:updated timestamp="2012-04-16T16:52:59Z">Appended parameter CONFDENS to configuration file.</ns0:updated></ns0:parameter>
 <ns0:parameter category="2sel" inuse="1">
  <ns0:name>SNRCUT</ns0:name>
  <ns0:value dtype="float">3.0</ns0:value>
  <ns0:comment>The cut in expected Signal-to-Noise below which no sources are selected. The Signal-to-Noise is determined from the estimated FWHM and the results of the aperture spectrophotometry .</ns0:comment>
  <ns0:updated timestamp="2011-09-01T16:18:18Z">Appended parameter SNRCUT to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="2sel" inuse="1">
  <ns0:name>BINRAD</ns0:name>
  <ns0:value dtype="float">0.3</ns0:value>
  <ns0:comment>The minimum spatial separation [measured in units of the expected FWHM] of two resolved sources. Resolved sources with distances smaller BINRAD are combined.</ns0:comment>
  <ns0:updated timestamp="2011-09-01T16:25:46Z">Appended parameter BINRAD to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="3fit" inuse="1">
  <ns0:name>GLOBSKY</ns0:name>
  <ns0:value dtype="bool">True</ns0:value>
  <ns0:comment>Flag indicating if additional components should be included to account for an unresollved background or the sky. The behaviour of these components can be controlled with the SKYSIZE parameter.</ns0:comment><ns0:updated timestamp="2011-11-28T19:40:14Z">Appended parameter GLOBSKY to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="3fit" inuse="1"><ns0:name>SKYSIZE</ns0:name><ns0:value dtype="float">-1.0</ns0:value><ns0:comment>The distance between two adjacent points in the grid used to model an unresolved background or the night sky. If set to a negative value only a constant background/sky componnent is used. Only has an effect if GLOBSKY is True.</ns0:comment><ns0:updated timestamp="2014-12-01T13:36:29Z">Appended parameter SKYSIZE to configuration file.</ns0:updated></ns0:parameter><ns0:parameter category="2sel" inuse="1">
  <ns0:name>USEUNRES</ns0:name>
  <ns0:value dtype="bool">False</ns0:value>
  <ns0:comment>Flag indicates whether the contribution from the unresolved sources should be included as an additional component in the analysis.</ns0:comment>
  <ns0:updated timestamp="2011-09-01T16:28:29Z">Appended parameter USEUNRES to configuration file.</ns0:updated>
 </ns0:parameter><ns0:parameter category="2sel" inuse="1"><ns0:name>UNRESBIN</ns0:name><ns0:value dtype="float">2.0</ns0:value><ns0:comment>Only has an effect if USEUNRES is enabled. In that case the contribution of the sources in the magnitude interval of width UNRESBIN below the confusion limit is combined in an unresolved stellar component</ns0:comment><ns0:updated timestamp="2012-04-16T16:45:23Z">Appended parameter UNRESBIN to configuration file.</ns0:updated></ns0:parameter>
 <ns0:parameter category="0general" inuse="1">
  <ns0:name>SMALLIFU</ns0:name>
  <ns0:value dtype="bool">True</ns0:value>
  <ns0:comment>This flag defines how the determination of the PSF and the coordinate transformation is performed during the fit. If SMALLIFU is enabled, all sources are used for this purpose (recommended for IFUs with a small number of spatial pixels), otherwise bright, isolated stars are used (recommended for MUSE)</ns0:comment>
  <ns0:updated timestamp="2011-11-28T19:37:02Z">Appended parameter SMALLIFU to configuration file.</ns0:updated>
 </ns0:parameter>

 
 <ns0:parameter category="3fit" inuse="1"><ns0:name>USESIGMA</ns0:name><ns0:value dtype="bool">True</ns0:value><ns0:comment>A flag indicating if the uncertainties of the IFS data should be used in the extraction.</ns0:comment><ns0:updated timestamp="2014-12-03T15:12:00Z">Appended parameter USESIGMA to configuration file.</ns0:updated></ns0:parameter><ns0:parameter category="3fit" inuse="1"><ns0:name>LAYERRNG</ns0:name><ns0:value dtype="tuple">(0, -1)</ns0:value><ns0:comment>The spectral range of the datacube that should be analysed, given as the indices of the first and the last layer in that range. By default, the whole cube is analysed.</ns0:comment><ns0:updated timestamp="2013-03-26T14:10:43Z">Appended parameter LAYERRNG to configuration file.</ns0:updated></ns0:parameter><ns0:parameter category="3fit" inuse="1">
  <ns0:name>PSFRAD</ns0:name>
  <ns0:value dtype="float">10.0</ns0:value>
  <ns0:comment>The radius out to which the PSF of a source will be defined. Should be large enough to avoid annuli of flux around the brighter sources in the residuals</ns0:comment>
  <ns0:updated timestamp="2011-10-25T13:49:50Z">Appended parameter PSFRAD to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="3fit" inuse="1">
  <ns0:name>POSFIT</ns0:name>
  <ns0:value dtype="int">2</ns0:value>
  <ns0:comment>Defines how source positions are handled in the fit:</ns0:comment>
  <ns0:comment>0 - Sources are fixed to their input positions.</ns0:comment>
  <ns0:comment>1 - Only a global offset is fitted.</ns0:comment>
  <ns0:comment>2 - A global offset and scaling are fitted.</ns0:comment>
  <ns0:comment>3 - Individual positions are fitted.</ns0:comment>
  <ns0:updated timestamp="2011-09-09T11:49:56Z">Appended parameter POSFIT to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="3fit" inuse="1">
  <ns0:name>PSFTYPE</ns0:name>
  <ns0:value dtype="str">moffat</ns0:value>
  <ns0:comment>The analytical profile that is used to model the PSF.</ns0:comment>
  <ns0:updated timestamp="2011-09-09T12:02:53Z">Appended parameter PSFTYPE to configuration file.</ns0:updated>
 </ns0:parameter>
 <ns0:parameter category="3fit" inuse="1">
  <ns0:name>PSFPARS</ns0:name>
  <ns0:value dtype="tuple">(2.5, 3.0, 0.0, 0.0)</ns0:value>
  <ns0:comment>The initial values of the PSF shape parameters. The meaning of the parameters for the individual profiles can be found in the manual.</ns0:comment>
  <ns0:updated timestamp="2011-09-09T12:08:06Z">Appended parameter PSFPARS to configuration file.</ns0:updated>
 </ns0:parameter>
